"37": "http://oct2017-plants.ensembl.org"
"40": "http://jul2018-plants.ensembl.org"
"45": "http://sep2019-plants.ensembl.org"
"49": "http://nov2020-plants.ensembl.org"
"52": "http://dec2021-plants.ensembl.org"
"56": "http://feb2023-plants.ensembl.org"
"57": "http://plants.ensembl.org"
