"37": "http://oct2017-bacteria.ensembl.org"
"40": "http://jul2018-bacteria.ensembl.org"
"45": "http://sep2019-bacteria.ensembl.org"
"49": "http://nov2020-bacteria.ensembl.org"
"52": "http://dec2021-bacteria.ensembl.org"
"56": "http://feb2023-bacteria.ensembl.org"
"57": "http://bacteria.ensembl.org"
